name: Semantic Release and Docker Publish

on:
  push:
    branches:
      - main

jobs:
  versioning:
    uses: GEWIS/actions/.github/workflows/versioning.yml@v1

  release:
    needs: versioning
    if: ${{ needs.versioning.outputs.next-version != '' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    container:
      image: docker:dind

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set safe Git directory
        run: git config --global --add safe.directory '*'

      - name: Set git info and version
        run: |
          echo "GIT_COMMIT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
          echo "GIT_COMMIT_BRANCH=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV
          echo "DOCKER_VERSION=${{ needs.versioning.outputs.next-version }}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.DOCKER_VERSION }}
            ghcr.io/${{ github.repository }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            GIT_COMMIT_SHA=${{ env.GIT_COMMIT_SHA }}
            GIT_COMMIT_BRANCH=${{ env.GIT_COMMIT_BRANCH }}
            DOCKER_VERSION=${{ env.DOCKER_VERSION }}
